// GENERATED by tools/sync-config.sh. Do not edit.

/** Short commit this build was made from, or "unknown" outside a checkout. */
export const COMMIT = '7db6a3b';

/** When it was made, UTC. */
export const BUILT_AT = '2026-09-04T05:33Z';
