#!/usr/bin/env bash
# Copy the origin map into each application's document root.
#
# Each app is deployed as its own origin with its own root, so neither can
# import a file that sits above it. This is the one place the duplication is
# introduced, and it is mechanical, so the copies cannot drift.
set -euo pipefail
cd "$(dirname "$0")/.."
for app in vault host; do
  {
    echo "// GENERATED by tools/sync-config.sh from shared-config.js. Do not edit."
    cat shared-config.js
  } > "$app/config.js"
  echo "wrote $app/config.js"
done
