#!/usr/bin/env bash
# Copy the origin map into each application's document root.
#
# Each app is deployed as its own origin with its own root, so neither can
# import a file that sits above it. This is the one place the duplication is
# introduced, and it is mechanical, so the copies cannot drift.
set -euo pipefail
cd "$(dirname "$0")/.."
for app in vault host; do
  {
    echo "// GENERATED by tools/sync-config.sh from shared-config.js. Do not edit."
    cat shared-config.js
  } > "$app/config.js"
  echo "wrote $app/config.js"
done

# The stylesheet has the same problem for the same reason: two origins, two
# document roots, and neither may fetch from the other. It was being copied by
# hand, which is 800-odd lines kept identical on trust. Edit vault/ui/base.css;
# this makes the copy.
cp vault/ui/base.css host/ui/base.css
echo "wrote host/ui/base.css"
