#!/usr/bin/env bash
# Copy the origin map into each application's document root.
#
# Each app is deployed as its own origin with its own root, so neither can
# import a file that sits above it. This is the one place the duplication is
# introduced, and it is mechanical, so the copies cannot drift.
set -euo pipefail
cd "$(dirname "$0")/.."
for app in vault host; do
  {
    echo "// GENERATED by tools/sync-config.sh from shared-config.js. Do not edit."
    cat shared-config.js
  } > "$app/config.js"
  echo "wrote $app/config.js"
done

# The stylesheet has the same problem for the same reason: two origins, two
# document roots, and neither may fetch from the other. It was being copied by
# hand, which is 800-odd lines kept identical on trust. Edit vault/ui/base.css;
# this makes the copy.
for shared in base.css toast.js confirm.js; do
  cp "vault/ui/$shared" "host/ui/$shared"
  echo "wrote host/ui/$shared"
done

# Stamp the commit into both origins so a reader can match what is running to
# what is in the repository. There is no build step to read it from, so it is
# written here, and it says "unknown" rather than lying when git is unavailable.
COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo unknown)
BUILT=$(date -u +%Y-%m-%dT%H:%MZ)
for app in vault host; do
  cat > "$app/build.js" <<EOF
// GENERATED by tools/sync-config.sh. Do not edit.

/** Short commit this build was made from, or "unknown" outside a checkout. */
export const COMMIT = '${COMMIT}';

/** When it was made, UTC. */
export const BUILT_AT = '${BUILT}';
EOF
  echo "wrote $app/build.js ($COMMIT)"
done
